Repository Metron-Project/Simyan, pull requests merged in 2021-09, with the labels that each got.

#40 Update Datatypes
  .pre-commit-config.yaml
  Simyan/creator.py
  Simyan/creator_list.py
  Simyan/generic_entries.py
  Simyan/issue.py
  Simyan/issue_list.py
  Simyan/publisher.py
  Simyan/publisher_list.py
  Simyan/story_arc.py
  Simyan/story_arc_list.py
  Simyan/volume.py
  Simyan/volume_list.py
  poetry.lock
  pyproject.toml
  tests/test_creators.py
  tests/test_volumes.py
Labels: Type: Improvement

#42 Documentation
  .flake8
  .pre-commit-config.yaml
  .readthedocs.yml
  Simyan/__init__.py
  Simyan/creator.py
  Simyan/creator_list.py
  Simyan/exceptions.py
  Simyan/generic_entries.py
  Simyan/issue.py
  Simyan/issue_list.py
  Simyan/publisher.py
  Simyan/publisher_list.py
  Simyan/session.py
  Simyan/sqlite_cache.py
  Simyan/story_arc.py
  Simyan/story_arc_list.py
  Simyan/volume.py
  Simyan/volume_list.py
  docs/Makefile
  docs/make.bat
  docs/source/Simyan.rst
  docs/source/about.rst.inc
  docs/source/conf.py
  docs/source/index.rst
  docs/source/install.rst
  docs/source/modules.rst
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/test_creators.py
  tests/test_init.py
  tests/test_issues.py
  tests/test_publishers.py
  tests/test_story_arcs.py
  tests/test_volumes.py
Labels: Type: Documentation

#47 Update dependencies
  .pre-commit-config.yaml
  README.md
  Simyan/__init__.py
  poetry.lock
  pyproject.toml
Labels: Type: Documentation, Type: Maintenance
